# Generated by Django 4.2.3 on 2023-09-06 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categroyid', models.AutoField(primary_key=True, serialize=False)),
                ('categroyname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('reviewString', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('stock', models.IntegerField()),
                ('isAvaiable', models.BooleanField(default=True)),
                ('publication_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='bookcovers/')),
                ('borrowedby', models.ManyToManyField(blank=True, related_name='borrowedbyRelated', to=settings.AUTH_USER_MODEL)),
                ('cat', models.ManyToManyField(blank=True, related_name='catRelated', to='bookmanagement.category')),
                ('review', models.ManyToManyField(blank=True, related_name='reviewRelated', to='bookmanagement.review')),
            ],
        ),
    ]
