# Generated by Django 4.2.3 on 2023-09-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
