# Generated by Django 4.2.3 on 2023-09-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categroyname',
            new_name='categoryname',
        ),
    ]
