# Generated by Django 4.2.3 on 2023-09-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanagement', '0004_rename_categroyname_category_categoryname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewGivenBy',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewOnBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
